### ISSUE TITLE
7.2 “结构化查询”中的“合并多子句”小节中的“email spam”没有明确翻译出来，意思是“垃圾邮件”

### ISSUE THREAD

**Issue by ScsUndefined** [looly/elasticsearch-definitive-guide-cn#119]
7.2结构化查询中的 合并多子句 小节中，es的示例代码中以email邮箱为例示范了合并多子句的功能，其中示例代码中
```
{
    "bool": {
        "must": { "match":      { "email": "business opportunity" }},
        "should": [
             { "match":         { "starred": true }},
             { "bool": {
                   "must":      { "folder": "inbox" }},
                   "must_not":  { "spam": true }}
             }}
        ],
        "minimum_should_match": 1
    }
}
```
这其中的spam，指的是 email spam 意思是垃圾邮件的意思，具体可以参见英文版维基
[https://en.wikipedia.org/wiki/Email_spam](https://en.wikipedia.org/wiki/Email_spam
)
但是译文中并没有明确翻译出spam的意思。望修正。
另外翻译辛苦了～～～～

最后 ad hoc 貌似也没有明确翻译出来，这个词的意思是特制的，特定的，具体可以参见百度百科
[http://baike.baidu.com/view/28428.htm#1](http://baike.baidu.com/view/28428.htm#1)

**Comment by looly** [comment]
感谢。现在这个翻译已经停止。请参阅https://github.com/elasticsearch-cn/elasticsearch-definitive-guide
