### ISSUE TITLE
错字

### ISSUE THREAD

**Issue by LanceHuang** [looly/elasticsearch-definitive-guide-cn#125]
1. 入门-->1.6 搜索-->全文搜索-->

> 但是为什么Jane Smith也会出现在结果里呢？原因是“rock”在她的abuot字段中被提及了。因为只有“rock”被提及而“climbing”没有，所以她的_score要低于John。

其中abuot应改为about

**Comment by looly** [comment]
谢谢~~ @see https://github.com/elasticsearch-cn/elasticsearch-definitive-guide
