### ISSUE TITLE
我用七牛云的景象加速，又弄了个在线阅读的站点，国内访问还是比较快的

### ISSUE THREAD

**Issue by luodaoyi** [looly/elasticsearch-definitive-guide-cn#131]
[esdoc.luody.info](http://esdoc.luody.info)

七牛审核需要十几分钟，这条issues发了30分钟之后 就可以访问了
内容一个字母都没有改，只是为了访问的速度，这几天一直再看 感谢这个项目！@looly

**Comment by looly** [comment]
哈哈，谢谢。不过我个人经历和能力有限，现在有团队在翻译这本书，欢迎关注：https://github.com/elasticsearch-cn/elasticsearch-definitive-guide
