### ISSUE TITLE
关于indexing=索引

### ISSUE THREAD

**Issue by RingoGit** [looly/elasticsearch-definitive-guide-cn#133]
indexing应当翻译为建立索引,而不是索引,
index = 索引,  indexing大概可以理解为doing index 的感觉,所以是建立索引
中文中索引有两种意思,名词大概是"目录"的意思,动词是"检索"的意思
检索是读操作,建立索引是写操作,强行把"索引"定义为存储数据的行为,,,有悖常理..
我们程序员和非程序员沟通本来就已经很费劲了,,建议还是不要让更费劲了~

**Comment by looly** [comment]
此处确实不太容易区分。感谢意见。
新版翻译已经在进行，请关注：
https://github.com/elasticsearch-cn/elasticsearch-definitive-guide
