### ISSUE TITLE
请问本书使用的是哪一个版本？

### ISSUE THREAD

**Issue by Jaggle** [looly/elasticsearch-definitive-guide-cn#136]
看到es版本变化太大了，今年（2016）三月份还是2.3.0，现在（2016.11.15）就已经5.0版本了，书中讲的一些安装方式和查询方法好像很多不适用。

所以我想先使用书中所使用的版本，等熟悉之后有空余时间再切换到新版本上去。

非常感谢！

**Comment by hsyan2008** [comment]
好像是1.4.0，看安装那个章节，有显示版本信息

**Comment by Jaggle** [comment]
3Q @hsyan2008

**Comment by looly** [comment]
1.4，最新的翻译已经到 https://github.com/elasticsearch-cn/elasticsearch-definitive-guide 感谢支持
