### ISSUE TITLE
关于query sdl可以给出一份详细的参考手册么？

### ISSUE THREAD

**Issue by janryWang** [looly/elasticsearch-definitive-guide-cn#14]
你好，非常感谢你能贡献一个es权威指南翻译资料，这本资料对于初学者来说真是非常有用，但是我对于query sdl基本还是一片空白，需要全面的了解一下它的查询语句才能融汇贯通，不知道你还有没有额外的时间贡献出来呢？

**Comment by looly** [comment]
有时间我会翻译相关部分。这个在第7章。

**Comment by janryWang** [comment]
@looly 好的，感谢
