### ISSUE TITLE
关于翻译的建议

### ISSUE THREAD

**Issue by allen8807** [looly/elasticsearch-definitive-guide-cn#49]
1.对于ES里的一些专业特定名词是否可以考虑保留英文原文，例如index，type，field，document之类的？
2.是否可以考虑在Markdown源文件里以注释的形式保留翻译原文，以方便校对？

**Comment by looly** [comment]
1. 关于保留原文这个暂未考虑。原文可以到[https://github.com/elastic/elasticsearch-definitive-guide](https://github.com/elastic/elasticsearch-definitive-guide)找到（我觉得原文附在翻译文中并不利于校对）

2. 专有名词我会部分翻译成中文，在括号内附原文英文。

**Comment by looly** [comment]
谢谢你的意见~~
