### ISSUE TITLE
哪些章节已有人认领有说明吗？别重复劳动了。。。

### ISSUE THREAD

**Issue by Kinghack** [looly/elasticsearch-definitive-guide-cn#61]
谢谢。

**Comment by looly** [comment]
现在没有规划。都是自愿翻译。你具体看下吧。如果有兴趣，可以挑自己喜欢的章节翻译~

**Comment by birdroidcn** [comment]
@looly 
现在还没计划？
我打算翻译11章『深入分片』，有人在翻译么？

**Comment by looly** [comment]
可以翻译。你看还未翻译的部分都可以翻译~

2015-08-13 20:40 GMT+08:00 birdroidcn <notifications@github.com>:
