### ISSUE TITLE
GitBook 貌似不打算继续使用 io 域名了，可以修改下（GitBook）项目主页的链接

### ISSUE THREAD

**Issue by kxxoling** [looly/elasticsearch-definitive-guide-cn#69]
不太确定，不过直接打开 io 域名的链接 Chrome 会报证书错误（网站提供的是 gitbook.com 的证书），打开 gitbook.io 会跳转到 gitbook.com。

**Comment by looly** [comment]
哪个链接证书报错？我这边都正常啊~~

Gitbook官方提供的域名是gitbook.io

**Comment by kxxoling** [comment]
https://www.gitbook.io/book/looly/elasticsearch-the-definitive-guide-cn/ 这个

**Comment by looly** [comment]
你访问 http://es.xiaoleilu.com/

github.io貌似是专门为了绑定域名跳转用的~

**Comment by kxxoling** [comment]
这个链接是可以的，不过貌似是因为 http 而不是 https。https 都逃不了这个问题，毕竟 gitbook 拥有的证书是颁发给 gitbook.com 的。

**Comment by looly** [comment]
刚看Gitbook文档，已经把CNAME域名换成gitbook.com了，我已经修改，再次感谢你的建议~~
