### ISSUE TITLE
关于"入门"一节中的"安装Marvel"

### ISSUE THREAD

**Issue by CoderIvan** [looly/elasticsearch-definitive-guide-cn#84]
在新的Marvel版本中已经不能按照[文档](http://wiki.jikexueyuan.com/project/elasticsearch-definitive-guide-cn/010_Intro/10_Installing_ES.html)这样安装了，详情参见[这里](https://www.elastic.co/downloads/marvel)

**Comment by jhush** [comment]
确实是，elasticsearch已经更新到2.1版本，但是权威指南还是1版本的，elastic官网有2版本的指南

**Comment by hzruandd** [comment]
@CoderIvan  你好，我已经按照https://www.elastic.co/downloads/marvel说明完成了安装，服务也都启动了，目前可以正常访问9200端口对应的elasticsearch服务，但是marvel这个插件提供的http管理页面却无法进入：
curl -i http://121.41.22.252:9200/_plugin/marvel/
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=UTF-8
Content-Length: 0

➜  ~ curl -i http://121.41.22.252:9200/_plugin/marvel/sense
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=UTF-8
Content-Length: 0

➜  ~ curl -i http://121.41.22.252:9200/               
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Content-Length: 318

{
  "name" : "Architect",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.3.1",
    "build_hash" : "bd980929010aef404e7cb0843e61d0665269fc39",
    "build_timestamp" : "2016-04-04T12:25:05Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}

但是我之前用1.x.x版本就可以很便捷去通过http页面和elasticsearch做交互。

**Comment by jhush** [comment]
十分感谢，问题已解决，之前使用2.x版本，后来使用1.7.4正常使用


来自 魅蓝 metal

-------- 原始邮件 --------
发件人：jake <notifications@github.com>
时间：周一 4月11日 上午 10:57
收件人：looly/elasticsearch-definitive-guide-cn <elasticsearch-definitive-guide-cn@noreply.github.com>
抄送：jhush <recessionxu@163.com>
主题：Re: [looly/elasticsearch-definitive-guide-cn] 关于"入门"一节中的"安装Marvel" (#84)

**Comment by CoderIvan** [comment]
@hzruandd 

非常感谢您的帮助，因为有一段时间了，暂时没时间去验证，既然已经处理完了，就直接close这个ISSUE了
